development:
  adapter: postgresql
  encoding: unicode
  template: template0
  database: chat_development
  pool: 10
  host: <%= ENV['RAILS_DATABASE_HOST'] %>
  username: <%= ENV['RAILS_DATABASE_USERNAME'] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  template: template0
  database: chat_test
  pool: 10
  host: <%= ENV['RAILS_DATABASE_HOST'] %>
  username: <%= ENV['RAILS_DATABASE_USERNAME'] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  template: template0
  database: chat_production
  pool: 10
  host: <%= ENV['RAILS_DATABASE_HOST'] %>
  username: <%= ENV['RAILS_DATABASE_USERNAME'] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
