source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.0.0'
gem 'sqlite3'
gem 'puma'
gem 'jbuilder'
gem 'config'
gem 'newrelic_rpm'
gem 'pg'
gem 'redis-rails'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'factory_girl_rails'
end

group :development do
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
  gem 'bullet'
  gem 'annotate'
  gem 'foreman'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
  gem 'hirb-unicode'

end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
